apiVersion: v1
kind: pod
metadata:
  name: redisapp-pod
  labels:
    name: redise-app-pod
    app: demo-voting-app

spec:
  containers:
    - name: redis-app
      image: dockersamples/examplevotingapp_redis
      ports:
        - containerPort: 6379